### ISSUE TITLE
[RPi] Games issues

### ISSUE THREAD

**Issue by nemo93** [libretro/snes9x#66] opened 2017-08-31 12:22 UTC
I'm carefully and thoroughly testing games with this core on Retropie latest version (on RPi3). Everything is being up to date on my system (including Raspbian packages). It went well so far except with the following games:

- **Chou Aniki Bakuretsu Rantouden** (Japan): game doesn't launch. Go straight into black screen and stays there. Not working on Snes9x1.53 & 1.54.1 Windows either but apparently does work on Bsnes or Zsnes. Regession confirmed => #187
- **Deae Tonosama Appare Ichiban** (Japan): this one does launch. However it goes on a very weird animated screen with an even weirder character and.. that's all. Pushing buttons does nothing. It does work with Snes9x1.53 & 1.54.1 on Win and doesn't display that weird screen on this Snes9x version.
- **JoJo no Kimyou na Bouken** (Japan): this one does launch. However screen goes full with garbage character during intro. Same issue on Snes9x 1.54.1 Win.
~~- Sailor Moon: graphical glitch. Right after character selection screen there's an intro screen with a spotlight moving around the screen and spotlight is "glitchy"/doesn't display properly.~~
- **Marko's Magic Football** (Europe): crash during intro / unplayable. Same issue on Snes9x 1.54.1 Win (crashes the emulator!).
- **Sufami Turbo chip games** launch but can't pass the instruction screen. I believe this is due on how ST games are supposed to work. Some ST games: Gekisō Sentai Carranger: Zenkai! Racer Senshi, Crayon Shin Chan, Sailor Moon Stars Panic 2, Gegege No Kitarou, ...
- **Final Fantasy VI (1)**: I got sound crackling/stuttering at some locations only (Figaro South is a good example). Just go to these locations and you'll be able to hear the sound crackling from time to time.
- **Final Fantasy VI (2)**: after a battle it may happen that the screen keeps on doing the mosaic effect in the background. It's annoying but it could go away simply by entering another battle.

**Comment by hizzlekizzle** [comment] 2017-08-31 13:13
> Sailor Moon: graphical glitch. Right after character selection screen there's an intro screen with a spotlight moving around the screen and spotlight is "glitchy"/doesn't display properly.

This one's actually working as intended. It's supposed to look like a spotlight hitting a stage.

For the ones that work in standalone v1.53, have you tested them with v1.54.1? There were some substantial changes to the emulator between those versions that could be causing these issues.

**Comment by nemo93** [comment] 2017-08-31 16:44
Re Sailor Moon => silly me. Then I've updated my initial post after testing with 1.54.1 (x64 on Win10). Same outcomes basically than with libretro.

**Comment by hizzlekizzle** [comment] 2017-09-01 03:06
Glad to hear it's not just us :)

Thanks for the report. I'll close this issue now since it's reported upstream, but feel free to reopen it if needed.

**Closed by hizzlekizzle** 2017-09-01 03:06 UTC

**Comment by nemo93** [comment] 2017-09-01 09:10
indeed :) Watch out as within the list there's one game that does work on upstream no problem => Deae Tonosama Appare Ichiban. There must be an issue with this fork of Snes9x then (keep me honest). I'm fine opening a ticket just for that game if that helps.
